homeassistant:
  name: Alys House
  latitude: !secret home_lat
  longitude: !secret home_lng
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml 

frontend: 
config: 
updater: 
discovery: 
history: 
logbook: 
map: 
cloud: 
wemo: 
ios: 
sun:

zone: !include zones.yaml
sensor: !include_dir_merge_list sensors
weather:
  - platform: yweather
    name: Weather 
media_player:
  - platform: roku 
camera: !include cameras.yaml
device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password 

#usps:
#    username: !secret usps_username
#    password: !secret usps_password
#    driver: phantomjs

mqtt: !include mqtt.yaml
ifttt:
  key: !secret ifttt_key
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
